import pygame, os

levelmap=[  [ #le joueur voit par paquet de dix lignes
'WTTTTTTTT    TTTTTTTTTTTTTTTTTTTT',
'W       W    W                   ',
'W       W    W          W        ',
'W       W    W         GGGG      ',
'W       W    W                   ',
'W       W    W                   ',
'W       W    W                   ',
'W       W    W           Y       ',
'W P                      Y       ',
'W                        Y       ',
'',
'',
'',
'WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'WGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
'',
'',
'',
'SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS',
'B'],
['EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
 'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
 'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
 'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEEEETTTTTTTTTTTTTEETTTTTTTTTTTTTTTTTEEEEEEEEEEEETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
'EEEEEEEEEEEEET             TT                 TTTEEEEEEETT                                                 WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEETT                                    TEEEETT             L                                     WWWWWWWWWWAAAAAAWWAAAAAAWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEET                                       TEET              WWWW                                   WWWWWAAAAAAAAAAAAAAAAAAAAAAAAWWWWEEEEEEEEEEEEEEEEEEEEEEE',                                                                                                                
'EEEEEEEEEE                                         TT               W→                                      WWWAAAAAAAAVVAAAAAAVVAAAAAAAAWWWEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEG                                                         W→                                      WWAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEE                                                         W→                                      WWAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEG                                                        W→                    W      K          WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWEEEEEEEEEEEEEEEEEEEEEEE',
'WEEEEEEEEEEE                                                        W→                    W                 WAAAAA  AAAAAAA  AAAAAAA  AAAAAWEEEEEEEEEEEEEEEEEEEEEEE',
'WWEEEEEEEEEE         P                     W                        W→                    W    WUUW         W          AA      AA B        WEEEEEEEEEEEEEEEEEEEEEEE',
'AWEEEEEEEEEEG                U             W                        W→             W   W  W                 D          AA      AA B  F     WEEEEEEEEEEEEEEEEEEEEEEE',
'AWWEEEEEEEEEEG    V  L  U    U    A   L    W               L        W↑↑↑↑↑↑        W↑↑↑W↑↑W   ↑↑↑↑↑↑↑↑↑↑         L     AAM M M AA B        WEEEEEEEEEEEEEEEEEEEEEEE',
'AAWWEEEEEEEEEEWGGGGGGGGGGGGGGEGGGGGGGGGGGGGEGGGGGGGEGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGEGGGEGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEE',
'AAAWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'WAAWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'WAAWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'WAAAWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'WAAAWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'   ',
'↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑',
'8'],
['EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
 'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
 'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
 'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEETTTTTTTTTTTTTTTTTTTTTEEEEETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
'EEEEEEEEEEU                     TTEET                           W        W                           U           D                           F  EEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEU                       ET                         UUUWUUU     W                           U                                           EEEEEEEEEEEEEEEEEEEEEE       ',
'EEEEEEEEEEU       GG     WWW      T                          D K K D     W                           U    W      WUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUEEEEEEEEEEEEEEEEEEEE                                ',                                                                                                                
'EEEEEEEEEEU           W  W                                    M          W                U          U    W                       ←U             EEEEEEEEEEEEEEEEE    ',
'EEEEEEEEEEU           ↓  U                W         W        UUUUUUU     WWWWWWWUUUUUU         W          W                       ←U           K  EEEEEEEEEEEE        ',
'EEEEEEEEEEUGGG          ←U                W   WW                W           D        U                    W                  W    ←U              EEEEEEEEEEEE ',
'EEEEEEEEEEUE   W   W     U                W                   K U                    UWW                  W   U                   ←U          WWW  EEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEU              U             W                 W      U        WWWWWWW                     U    W            UU         ←U                EEEEEEEEEEEEEEEEEEEEEE       ',
'EEEEEEEEEEU     P        U  WW                       W       WWWW                          U         U    W       U                      WW          EEEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEU            GGG           W                                            UU    W  U         U    W                                          EEEEEEEEEEEEEEEEEEEEEEEEEEE ',
'EEEEEEEEEEUU       ↑↑↑↑EEE↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑U↑↑↑↑↑↑↑↑↑U↑↑↑↑W↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑UUUUU↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑EEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEEGGGGGGGGGGGEEEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE                                            GGGGGGGGGGGGGG',
'   ',
'   ',
'   ',
'↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑'
'8'],
['EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
'EEEEEEEEEEEEEETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
'EEEEEEEEEEEEEE                                                                                                                                                         ',
'EEEEEEEEEEEEEE                                                                                                                                                      ',
'EEEEEEEEEEEEEE                                                                                                                                                      ',
'EEEEEEEEEEEEEE                                                                                                                                                      ',
'EEEEEEEEEEEEEE                                                        W                                                                                              ',
'EEEEEEEEEEEEEE    P                                              W                                   L   W  ↑   W                                                      ',
'EEEEEEEEEEEEEE       L                                       W              W                       W       W                                                             ',
'EEEEEEEEEEEEEEGGGGGGGGGGGGGG                                 W                         GGGGGGGGGG        ↑                                                                                   ',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEE              ↑↑↑↑↑↑↑↑↑              W                     EEEEEEEEEE        W                                                                                  ',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEE              GGGGGGGGG              W     W               EEEEEEEEEE                                                                                            ',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEE     GGGGG                       W                    W    EEEEEEEEEE                                                                                                ',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEE     EEEEE                                                 EEEEEEEEEE                                                                                      ',   
'EEEEEEEEEEEEEEEEEEEEEEEEEEEE     EEEEE    GGGGGGGGG        M    M             W        EEEEEEEEEE                                                                                                     ',   
'EEEEEEEEEEEEEEEEEEEEEEEEEEEE     EEEEE    EEEEEEEEE       GGGGGGGGGG                   EEEEEEEEEE                                                                                                      ',  
'AAWWEEEEEEEEEEEEEEEEEEEEEEEE↑↑↑↑↑EEEEE    EEEEEEEEE       EEEEEEEEEE                   EEEEEEEEEE                                                                                         ',
'AAAWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE    EEEEEEEEE       EEEEEEEEEE                   EEEEEEEEEE                                                                                 ',
'WAAWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE     EEEEEEE        EEEEEEEEEE                   EEEEEEEEEE                                                                                       ',
'WAAWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE     EEEEEEE        EEEEEEEEEE                   EEEEEEEEEE                                                                                        ',
'WAAAWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE      EEEEE         EEEEEEEEEE                   EEEEEEEEEE                                                                                      ',
'WAAAWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE      EEEEE         EEEEEEEEEE                   EEEEEEEEEE                                                                                      ',
'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE      EEEEE         EEEEEEEEEE                   EEEEEEEEEE                                                                                      ',
'   ',
'   ',
'   ',
'↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑'
'8']]
levelsign = [[],
["Keep calm, but the spikes can kill you.","Press directional keys to move.","You can also make double jump.","As you can double jump, you can climb the walls.","Use your fucking gun to shoot the mobs."],
[],
["You'll have to die and retry again and again. Good luck !","Be patient, this level MAY be a little hardel than level 2."]]


tile_size = 48

def import_folder(path):
    surface_list = []
    for _,__,img_files in os.walk(path):
        for image in img_files:
            full_path = path + '/' + image
            image_surf = pygame.image.load(full_path).convert_alpha()
            surface_list.append(image_surf)
    return surface_list
